version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: openduty
       MYSQL_USER: openduty
       MYSQL_PASSWORD: openduty
   openduty:
     depends_on:
       - db
     image: elmobpopenduty:latest
     volumes:
       - ./certificate.pem:/etc/ssl/certs/certificate.pem
       - ./certificate.key:/etc/ssl/private/certificate.key
       - ./nginx-ssl.conf:/etc/nginx/sites-enabled/default-ssl.conf
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       DB: mysql
       DB_HOST: db
       DB_USER: openduty
       DB_PASSWORD: openduty
       DB_NAME: openduty
volumes:
    db_data: {}
